### ISSUE TITLE
Problems Building on Visual Studio 2013

### ISSUE THREAD

**Issue by fb39ca4** [strukturag/libde265#103]
First off, something odd was happening when std::min and std::max were used. A #define appeared to be set for min and max, replacing them with nothing, but I was able to fix those errors by adding #undef min and #undef max at the start of the code in the relevant files.

Next, linker errors:

    Error	18	error LNK2019: unresolved external symbol "public: bool __cdecl encoder_picture_buffer::have_more_frames_to_encode(void)const " (?have_more_frames_to_encode@encoder_picture_buffer@@QEBA_NXZ) referenced in function en265_encode	C:\Users\____\Documents\GitHub\libde265\build\vc9-x86\en265.obj	dec265
    Error	19	error LNK2019: unresolved external symbol "public: void __cdecl encoder_picture_buffer::mark_image_is_outputted(int)" (?mark_image_is_outputted@encoder_picture_buffer@@QEAAXH@Z) referenced in function en265_free_packet	C:\Users\____\Documents\GitHub\libde265\build\vc9-x86\en265.obj	dec265
    Error	20	error LNK2019: unresolved external symbol "public: void __cdecl encoder_picture_buffer::release_input_image(int)" (?release_input_image@encoder_picture_buffer@@QEAAXH@Z) referenced in function en265_free_packet	C:\Users\____\Documents\GitHub\libde265\build\vc9-x86\en265.obj	dec265
    Error	21	error LNK2019: unresolved external symbol "public: __cdecl encoder_context::encoder_context(void)" (??0encoder_context@@QEAA@XZ) referenced in function en265_new_encoder	C:\Users\____\Documents\GitHub\libde265\build\vc9-x86\en265.obj	dec265
    Error	22	error LNK2019: unresolved external symbol "public: void __cdecl encoder_context::start_encoder(void)" (?start_encoder@encoder_context@@QEAAXXZ) referenced in function en265_start_encoder	C:\Users\____\Documents\GitHub\libde265\build\vc9-x86\en265.obj	dec265
    Error	23	error LNK2019: unresolved external symbol "public: enum de265_error __cdecl encoder_context::encode_picture_from_input_buffer(void)" (?encode_picture_from_input_buffer@encoder_context@@QEAA?AW4de265_error@@XZ) referenced in function en265_encode	C:\Users\____\Documents\GitHub\libde265\build\vc9-x86\en265.obj	dec265

**Comment by fancycode** [comment]
Which version/commit are you trying to compile? Could you please also provide the complete commandline you use?
