### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [strukturag/libde265#114]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/strukturag/libde265/blob/294243cde1fad98808a02c7686b1a07325161413/configure.ac#L81 "configuration checks")?

**Comment by fancycode** [comment]
We already check for the pthread library [here](https://github.com/strukturag/libde265/blob/294243cde1fad98808a02c7686b1a07325161413/configure.ac#L81). If you think this should be changed, we will happily accept a pull-request ;-)
