### ISSUE TITLE
Unable to compile arm optimizations with clang

### ISSUE THREAD

**Issue by Ivansss** [strukturag/libde265#116]
I got the following errors when trying to compile arm optimizations using clang.

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DHAVE_CONFIG_H -I. -I../..    -mfpu=neon -I.. -DHAVE_NEON -DEXTERN_ASM= -DHAVE_AS_FUNC -DHAVE_SECTION_DATA_REL_RO -g -O2 -c -o libde265_arm_neon_la-asm.lo `test -f 'asm.S' || echo './'`asm.S
clang: warning: argument unused during compilation: '-mfpu=neon'
asm.S:44:9: error: unknown directive
        .arch armv7-a
        ^
asm.S:54:9: error: unknown directive
        .fpu neon
        ^
asm.S:59:9: error: unknown directive
        .syntax unified
        ^
asm.S:60:3: error: unexpected token at start of statement
@ .thumb
  ^
asm.S:61:3: error: unexpected token at start of statement
@ .eabi_attribute 25, 1 @ Tag_ABI_align_preserved
  ^
asm.S:62:3: error: unexpected token at start of statement
@ .section .note.GNU-stack,"",%progbits @ Mark stack as non-executable
  ^

**Comment by LucasTizma** [comment]
@Ivansss: Any luck with this? Trying to figure out how to speed this up on iOS if possible.

**Comment by Alexander-Ushakov** [comment]
You must set arch flag to tell compiler to compile for ARM instead of x86:  "-arch armv7"
