### ISSUE TITLE
enc265: assertion failure in de265_image::alloc_image

### ISSUE THREAD

**Issue by miseri** [strukturag/libde265#117]
When trying to encode a yuv file with the enc265 application the following occurs:

`ImageSource_YUV::read_next_image()` on line 57 in image-io.cc calls `de265_image::alloc_image` with `sps = NULL`:

    img->alloc_image(width,height,de265_chroma_420, NULL, false,
                   NULL, NULL, 0, NULL, false);

which triggers the assertion on line 240 in image.cc `assert(sps);` crashing the program.

    de265_error de265_image::alloc_image(int w,int h, enum de265_chroma c,
                                     const seq_parameter_set* sps, bool allocMetadata,
                                     decoder_context* dctx,
                                     encoder_context* ectx,
                                     de265_PTS pts, void* user_data,
                                     bool useCustomAllocFunc)

The previous assertion is commented out:
`//if (allocMetadata) { assert(sps); }`

**Comment by farindk** [comment]
The encoder is still under heavy development and not yet ready for use. Current development is in the 'encoder' branch, but currently also broken because of big architectural changes.

**Comment by miseri** [comment]
Ok, thanks for the info. Do you have a (rough) estimate when the encoder will be ready? I'm planning to wrap the encoder in a DirectShow filter...
