### ISSUE TITLE
undeclared identifier NULL on FreeBSD

### ISSUE THREAD

**Issue by kwm81** [strukturag/libde265#119]
The following error happens when trying to build libde265 1.0.2 on FreeBSD. 

The newer FreeBSD releases use Clang as the default compiler, which give the error below. I have tested a old FreeBSD that still has GCC as default compiler build this code fine without any changes.

Disabling the #define in libde265/util.h fixes the build but I'm not sure that it is the right thing to do.

--

/bin/sh ../../../libtool  --tag=CXX   --mode=compile c++ -DHAVE_CONFIG_H -I. -I../../..    -I../.. -pipe -g -fstack-protector -fno-strict-aliasing  -Werror=return-type -Werror=unused-result -Werror=reorder -std=gnu++11 -DDE265_LOG_ERROR -MT libde265_encoder_algo_la-algo.lo -MD -MP -MF .deps/libde265_encoder_algo_la-algo.Tpo -c -o libde265_encoder_algo_la-algo.lo `test -f 'algo.cc' || echo './'`algo.cc
libtool: compile:  c++ -DHAVE_CONFIG_H -I. -I../../.. -I../.. -pipe -g -fstack-protector -fno-strict-aliasing -Werror=return-type -Werror=unused-result -Werror=reorder -std=gnu++11 -DDE265_LOG_ERROR -MT libde265_encoder_algo_la-algo.lo -MD -MP -MF .deps/libde265_encoder_algo_la-algo.Tpo -c algo.cc  -fPIC -DPIC -o .libs/libde265_encoder_algo_la-algo.o
In file included from algo.cc:23:
In file included from ../../../libde265/encoder/algo/algo.h:26:
In file included from ../../../libde265/encoder/encode.h:26:
../../../libde265/image.h:86:26: error: use of undeclared identifier 'NULL'
  MetaDataArray() { data=NULL; data_size=0; log2unitSize=0; width_in_uni...
                         ^
/usr/include/sys/_null.h:35:14: note: expanded from macro 'NULL'
#define NULL    nullptr
                ^
../../../libde265/util.h:75:17: note: expanded from macro 'nullptr'
#define nullptr NULL
                ^

**Comment by farindk** [comment]
Seems like Clang has its own definition of nullptr, leading to a circular definition loop.

I'm wondering why your Clang passes the "#if __GNUC__" check in libde265/util.h
I would expect that __GNUC__ is not defined.

**Comment by kwm81** [comment]
Clang sets __GNUC__ for compat reasons. I don't know the details. I think the easiest fix would be to add !defined(__clang__) to the GNUC check.

http://nadeausoftware.com/articles/2012/10/c_c_tip_how_detect_compiler_name_and_version_using_compiler_predefined_macros has a nice table.

**Comment by fancycode** [comment]
The clang on Ubuntu Precise doesn't have that problem (it's passing on Travis), that's why we didn't detect this yet. I updated the `configure` script to check if the compiler supports `nullptr`.

**Comment by kwm81** [comment]
The patch resolves the issue, thanks!
Though the comment in util.h probably needs to be updated also.

**Comment by fancycode** [comment]
Right, I changed it in #122.
