### ISSUE TITLE
Travis no longer green on master

### ISSUE THREAD

**Issue by fancycode** [strukturag/libde265#130]
Travis is no longer green on master after commit 0338ac5:
https://travis-ci.org/strukturag/libde265/builds/85284996

Also the fuzzing streams are failing after commit 8ec4e93:
https://travis-ci.org/strukturag/libde265/builds/85519474

Please check and make sure to keep Travis green/stable at least on the master branch in the future.

**Comment by farindk** [comment]
I tried to fix the CMakefile to find this include file, but could not
see where to add the path.

--------------------------

/home/travis/build/strukturag/libde265/dist-cmake-test/libde265-1.0.2/enc265/enc265.cc:30:10:
fatal error:

      'image-io-png.h' file not found

#include "image-io-png.h"

         ^

1 error generated.



2015-10-20 14:12 GMT+02:00 Joachim Bauch <notifications@github.com>:

**Comment by fancycode** [comment]
It is using the result of `make dist` which then fails to compile, maybe the header is new and not included in the distribution tarball?

**Comment by farindk** [comment]
That could be the reason.

However, I think it also failed when I tried to build it locally with cmake
without 'make dist'. Then I gave up.



2015-10-20 14:19 GMT+02:00 Joachim Bauch <notifications@github.com>:

**Comment by fancycode** [comment]
`cmake` without `make dist` is also tested, that works:
https://travis-ci.org/strukturag/libde265/jobs/85562561

**Comment by farindk** [comment]
Then it sounds like a simple fix.


2015-10-20 14:25 GMT+02:00 Joachim Bauch <notifications@github.com>:

**Comment by fancycode** [comment]
The missing file most likely yes, but I don't know about the fuzzing streams. Maybe you added an assertion somewhere that now fires?

**Comment by farindk** [comment]
Most probably an unavailable reference to a SPS or PPS header which are now
managed through shared_ptr<>s. Not too concerned about it. Will check later.


2015-10-20 14:31 GMT+02:00 Joachim Bauch <notifications@github.com>:

**Comment by farindk** [comment]
all green again
