### ISSUE TITLE
ss

### ISSUE THREAD

**Issue by figgis** [strukturag/libde265#134]
The output of tools/yuv-distortion always returns 0 for the 3nd column. The PSNR values are exactly the same as I get using other tools. 

```
$ ./yuv-distortion F1.yuv F2.yuv 1920 1072
0 26.194000 0.000000ng frame 1
1 25.950652 0.000000ng frame 2
2 25.734250 0.000000ng frame 3
3 26.296376 0.000000ng frame 4
4 26.298215 0.000000ng frame 5
5 26.324584 0.000000ng frame 6
6 26.671997 0.000000ng frame 7
7 26.365405 0.000000ng frame 8
8 26.250325 0.000000ng frame 9
9 26.915763 0.000000ng frame 10
10 26.747261 0.000000ng frame 11
...
```

Using commit: 503af1932461419666e6766b28f27a759b04f3fc

**Comment by figgis** [comment]
Title should be SSIM and not SS :-)

**Comment by farindk** [comment]
SSIM computation needs that you compile libde265 with libvideogfx installed. When running "configure", make sure that it detects libvideogfx.
