### ISSUE TITLE
Support for Raspian Jessie

### ISSUE THREAD

**Issue by firepro20** [strukturag/libde265#135]
Trying to install on Raspian Rasbperry Pi3 and giving me an error could not find a distribution template for Raspian

**Comment by farindk** [comment]
Could you please copy-paste the output of the 'configure' command and compile command here?
I'm not sure what you mean.

**Comment by firepro20** [comment]
Im trying to install the ppa repository on Raspbian Jessie

**Comment by fancycode** [comment]
As Raspbian is based on Debian, you should be able to use the official Debian packages:
https://packages.debian.org/source/libde265

**Comment by firepro20** [comment]
Hi,

I wanted to let you know about this petition I just started on Change.org,
"Rockstar Games: Development of Empire Earth IV".
You can read more about it and sign the petition here:

https://www.change.org/p/rockstar-games-development-of-empire-earth-iv?recruiter=132240640&utm_source=starters_petition_mgmt&utm_medium=email&utm_campaign=petition_mgmt_5_sigs_emailed_by_starters

Thank you!

Daniel Zammit
