### ISSUE TITLE
SHVC decoding option.

### ISSUE THREAD

**Issue by JWSon** [strukturag/libde265#137]
Hi  :)
I am going to ask a question about something that is important for what I am going to do.
I’ve tried to build libde265(master branch)  and I just compile it successfully.

However, I don't know what is the SHVC decoding option.
It only decodes layer0. I wnat to decode the other layers.

I look forward to your responses.
Thanks!

**Comment by farindk** [comment]
Hi,
the master branch does not have the SHVC option. There is a separate SHVC branch with support for it, but it is not maintained with a high priority.
Regards,
  Dirk

**Comment by JWSon** [comment]
Thanks for your response.
I tried to build the SHVC branch on ubuntu , but it doesn't have CmakeLists.txt.
Also, compiling build.bat file failed on window 64bit.
How to build the SHVC branch on ubuntu or window?
Regard,
Son

**Comment by farindk** [comment]
On Linux, follow these steps:
./autogen.sh
./configure
make
