### ISSUE TITLE
Small issue for newer(?) FFmpeg header in sherlock265

### ISSUE THREAD

**Issue by YggdrasiI** [strukturag/libde265#141]
Hello,

the following lines in sherlock265/VideoDecoder.cc could be problematic:
``
// Support compiling against old versions of FFmpeg/libav.
#ifndef AV_PIX_FMT_BGRA
#define AV_PIX_FMT_BGRA PIX_FMT_BGRA
#endif
#ifndef AV_PIX_FMT_YUV420P
#define AV_PIX_FMT_YUV420P PIX_FMT_YUV420P
#endif
``

This fallback work not as aspected.  The above constants are defined in an enum and not 'as #define'.
Thus, the #ifndef-expression returns true.
This leads to (GCC 4.8.4) :

``g++ -DHAVE_CONFIG_H -I. -I..  -I../libde265  -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/u
sr/include/qt4/QtGui   -std=c++0x -fPIC  -I/usr/local/include   -g -O2 -Werror=return-type -Werror=unused-
result -Werror=reorder -std=gnu++11 -DDE265_LOG_ERROR -MT sherlock265-VideoDecoder.o -MD -MP -MF .deps/she
rlock265-VideoDecoder.Tpo -c -o sherlock265-VideoDecoder.o `test -f 'VideoDecoder.cc' || echo './'`VideoDecoder.cc
VideoDecoder.cc: In member function ‘void VideoDecoder::convert_frame_swscale(const de265_image*, QImage&)’:
VideoDecoder.cc:40:28: error: ‘PIX_FMT_YUV420P’ was not declared in this scope
 #define AV_PIX_FMT_YUV420P PIX_FMT_YUV420P
``

Solution: Comment above lines out.

Regards, Olaf Schulz

**Comment by farindk** [comment]
Fixed. Thank you!
