### ISSUE TITLE
how to enable wpp support

### ISSUE THREAD

**Issue by MR0MIKE** [strukturag/libde265#148]
Hi :）,

thanks for your work. currently, I try study about H265 encode/decode. first I try to encode the video by your demo enc265, however it failed during the process .
error:  "  enc265: /home/ubuntu/Code/libde265-master/libde265/encoder/encoder-syntax.cc:1483: void encode_coding_unit(encoder_context*, CABAC_encoder*, const enc_cb*, int, int, int, bool): Assertion `cb->split_cu_flag == 0' failed.
Aborted (core dumped) "

So I encode the video using x265 , and try to decode it by demo dec265, it works, but it is a bit slow. I want to use multi-thread mode, but  it print "WARNING: Cannot run decoder multi-threaded because stream does not support WPP", speed is not improved. 

could u please tell me the reason and how to use multi-threaded in libde265? 
Thanks a lot.

**Comment by farindk** [comment]
Hi,
encoding is currently (Feb 2017) very limited and probably not very useful for general encoding tasks.

Usually, h265 is designed such that a stream has to be encoded using WPP or tiles to make use of multi-threading. However, you can now also check out the libde265 branch 'frame-parallel', which can decode several frames in parallel. It should be much faster than the current 'master' branch. The frame-parallel branch will soon become the new master branch.

Regards,
Dirk

**Comment by MR0MIKE** [comment]
cool, thanks for your answer.
