### ISSUE TITLE
How To Compile?

### ISSUE THREAD

**Issue by Pecacheu** [strukturag/libde265#149]
I'm on Windows, and I have CMAKE, MAKE, arm-none-eabi, and a GCC compiler installed, and I'm trying to compile for an ARM11 device. (No, I can't compile on the device, it's not running Linux.)

I need to decode H.265 video streaming over the local network on the device, and it doesn't have hardware h264 or h265 support. (It does however have hardware YUV <-> RGB, which is useful.)

The video is being muxed and demuxed in a custom audio/video format I wrote (I'll put it on GitHub when it's finished), because I got fed up with MP4 and MOV refusing to stream properly.

I tried just adding the 'libde265' folder to my project and compiling, but that didn't work.

First problem, my compiler isn't configured to recognize '.cc' extension, so I wrote a script to rename '.cc' to '.cpp' ('cause I like writing scripts.) The includes were written like `#include <libde265/whatever.h>`, so the compiler couldn't find the files. I wrote a script to fix that as well, which seemed to work. `de265-version.h` is missing, so I renamed `de265-version.h.in` to `de265-version.h` and manually put the version where it clearly goes. But even after all that, the compilation errors just kept piling up, so eventually I just gave up trying to solve them. Obviously, the library isn't meant to be compiled this way.

So then, how is it supposed to be compiled? I tried the instructions in the **Build** section of the README, but cmake just generates a bunch of useless garbage in the build folder, and make says it couldn't find a Makefile.

**Comment by Pecacheu** [comment]
I really need an answer on this. I have almost everything else working, encoding video and audio, muxing, streaming, demuxing, and decoding audio. Decoding the video is the only thing not working.

I'm using FFMPEG to encode H.265 on the Windows-based host, but I can't use it on the client to decode as well. The client is bare-metal, no OS. FFMPEG has too many dependencies, it can't be compiled for bare-metal.

**Comment by farindk** [comment]
The Makefiles are based on autoconf for Unix, that won't be easy for
Windows. However, the cmake files should work fine. We are running them on
our continuous integration tests and they work fine.
Since Windows does not have all the files needed, or cannot generate them
(like the de265-version.h), all additional files required for Windows are
in the "extra" directory.

If you still get errors, send us the compiler output so that we can answer
with useful comments.

Dirk


2017-05-26 22:54 GMT+02:00 Bryce <notifications@github.com>:

**Comment by Pecacheu** [comment]
Okay, now I'm getting an error about de265_thread_primitive does not name a type in threads.h. I don't think arm-none-eabi has a multi-threading library.

**Comment by farindk** [comment]
You are compiling for a target without OS running on it? That might indeed
be a bit challenging to get threads to work without OS.

If you absolutely need to, older versions of libde265 also run without
multi-threading. You will have to remove code that uses threads, but the
decoder can also work single threaded when the number of worker threads =
0. I think that should be possible with code from the "master" branch.
Newer versions of libde265 (in the "frame-parallel" branch) always require
multi-threading.


2017-05-28 22:13 GMT+02:00 Bryce <notifications@github.com>:

**Comment by Pecacheu** [comment]
Okay, I'm using the master branch now. Now I'm getting this error: `libde265/contextmodel.cpp:201:66: error: 'Clip3' was not declared in this scope`. I looked around a bit for Clip3, but I can't find it defined anywhere. It looks like a math function of some kind, so I googled for the formula, but to no avail.
