### ISSUE TITLE
Decoding problems using dec265 sample

### ISSUE THREAD

**Issue by novalain** [strukturag/libde265#151]
I'm trying to convert a sequence of images using ffmpeg and decode using the sample binary dec265, but no matter what I try I get 0 frames decoded. Settings used for encoding:

`ffmpeg -pattern_type glob -i "*.jp2" -c:v libx265 -preset medium -crf 28 -c:a aac -b:a 128k out.mp4`

**output**: 
`./dec265 out.mp4`
`nFrames decoded: 0 (0x0 @  0.00 fps)`

I also tried with videos from here: https://x265.com/hevc-video-files/. This gives the same output which seems weird.

I even tried with the sample video from the website (1720x720): http://www.libde265.org/downloads-videos/#. This is also giving me the same output but with some additional warnings `WARNING: non-existing PPS referenced`

Am I doing anything wrong?

**Comment by farindk** [comment]
Hi Michael,

dec265 reads raw h265 elementary streams. It does not read container
formats (mkv, mp4, m2v, ...).
There are tools available for extracting the video tracks from those
containers. A quick search will give you some options.

Dirk


2017-06-04 7:22 GMT+02:00 Michael Novén <notifications@github.com>:

**Comment by novalain** [comment]
Thanks a lot, got it to work with ffmpeg by changing `out.mp4` to `out.h265`.

May I ask if you may know anything about optimizing encode settings in ffmpeg to get the fastest decode rate possible in h265? I want to convert a sequence of still images to h265 and being able to decode each frame as fast as possible. If I need to sacrifice quality so be it.

**Comment by adhirmndl** [comment]
can anyone tell me, how to convert hevc rtp (received from a ip camera via rtsp) packets to raw bit-stream, which is input of ./dec265 (libde265), please help me, or give some sample code.
