### ISSUE TITLE
Extracting DCT coefficients for every frame in an encoded video.

### ISSUE THREAD

**Issue by ramitsawhney27** [strukturag/libde265#154]
I've been using the prebuild dec265 for decoding encoded binaries (.bin) videos. I saw that the acceleration-speed folder has methods for computing the DCT coefficients, however the make fails for acceleration-speed for me. Is there any way I can perhaps call a function via dec265 itself, so it writes all the DCT coefficients in a file as it runs the video?

**Comment by farindk** [comment]
You were looking at the wrong place. The "acceleration-speed" util is only
for testing the implementation of fast DCT algorithms.
If you want to extract DCT coefficients from video streams, you can tap
into "inv_transform()" in transform.cc.


2017-10-16 16:19 GMT+02:00 ramitsawhney27 <notifications@github.com>:

**Comment by ramitsawhney27** [comment]
Yes, I did see that, however due to the lack of documentation, it’s pretty tough to decipher how exactly I would do that. Could you perhaps tell me how exactly I can feed the command? Perhaps create a main function in Transform.cc, invoke inv_transform? I’m unaware of what arguments to pass to the function though. I would like to simply be able to run it as an executable as I would use dec265 vid.bin

**Comment by farindk** [comment]
Add this code:

template <class pixel_t>
void transform_coefficients(acceleration_functions* acceleration,
                            int16_t* coeff, int coeffStride, int nT, int
trType,
                            pixel_t* dst, int dstStride, int bit_depth, int
maxColumn,int maxRow)
{
  std::cout << "--------- transform size: " << nT << "\n";
  for (int r=0;r<nT;r++) {
    for (int c=0;c<nT;c++) {
      std::cout << coeff[r*coeffStride + c] << " ";
    }
    std::cout << "\n";
  }
  ...

Then run dec265 with -t0 to disable multi-threaded decoding.



2017-10-23 11:55 GMT+02:00 ramitsawhney27 <notifications@github.com>:

**Comment by ramitsawhney27** [comment]
I'm not quite sure where exactly to add this. Sorry I'm just having a hard time due to the lack of documentation again. I added the above function directly to dec265.cc and then used the make command, but I get an  error: unknown
      type name 'acceleration_functions'

Also, wouldn't I need to add code to call this function? Again with what parameters, sorry but it would be really very helpful if you could provide me some steps on exactly how to add to dec265 in order to get the DCT coefficients of a .bin file.

**Comment by farindk** [comment]
1) Open the file transform.cc.
2) There will be a function transform_coefficients().
3) Add the few lines from my previous response at the beginning of that
function.
4) add a #include <iostream> somewhere at the top, if necessary
5) compile
6) run dec265 and enjoy the output of DCT coefficients


2017-10-23 15:48 GMT+02:00 ramitsawhney27 <notifications@github.com>:

**Comment by ramitsawhney27** [comment]
Thank you so much! This has been an immense help. I have a question as well. Is there any possibility to similarly get Motion Vectors, I, B, P frames, CU/TU decoding etc? I had been using hm16.0 to calculate the above, but libde has been much faster and easier to use on my mac.

**Comment by farindk** [comment]
Yes, you can get it in a similar way. But you will have to search through
the source to find the right places yourself.

Hint: take the latest source from the "frame-parallel" branch, run
'configure' with --enable-logging and run dec265 with option "-vvv" (3
times -v).
This will output a lot of very low-level information. You can search the
source where this comes from and add the information you need.


2017-10-23 16:29 GMT+02:00 ramitsawhney27 <notifications@github.com>:

**Comment by praneet195** [comment]
Hi,
@farindk have you manage to extarct the CTU information?
