### ISSUE TITLE
How to enable trace?

### ISSUE THREAD

**Issue by kislayaranjan** [strukturag/libde265#156]
I have tried the recommended procedure and when that didn't work i tried manually defining the relevant macros used to enable printing traces at different levels

**Comment by farindk** [comment]
Assuming you are in the 'master' branch. The recommended procedure is to run ./configure with these flags:
  --enable-log-info       turn on logging at info level (default=no)
  --enable-log-debug      turn on logging at debug level (default=no)
  --enable-log-trace      turn on logging at trace level (default=no)

and then run dec265 with one or several -v switches. Each -v increases debugging level (up to three).
You may also want to run dec265 with -d to dump the headers.
