### ISSUE TITLE
Trouble installing / upgrading / updating recently (ubuntu 16 and apt-get)

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [strukturag/libde265#160]
Hello,

I have been having an issue for the past few days and I'm too noobish to see if it's on my end or on yours. I tried to find infos elsewhere (askubuntu mainly) but to no avail. I hope it's okay to ask here. I'm running Ubuntu 16.04.

I had already installed the source with `sudo add-apt-repository ppa:strukturag/libde265` a while back.

When casually running `sudo apt-get full-upgrade` I saw that `libde265` needed updating (it was a week ago or so, I'm not sure there were any package to upgrade with it but I don't think it really matters). And I got an error when trying to update it. So I decided to uninstall it (which also removed `vlc-plugin-libde265` to then readd it but got the same error.

The error is the following : 

> **sudo apt-get install libde265**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libde265
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/245 kB of archives.
After this operation, 701 kB of additional disk space will be used.
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend requires a screen at least 13 lines tall and 31 columns wide.)
debconf: falling back to frontend: Readline
(Reading database ... 437583 files and directories currently installed.)
Preparing to unpack .../libde265_1.0.2-1ppa2\~trusty1_amd64.deb ...
Unpacking libde265:amd64 (1.0.2-1ppa2\~trusty1) ...
dpkg: error processing archive /var/cache/apt/archives/libde265_1.0.2-1ppa2\~trusty1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libde265.so.0.0.10', which is also in package libde265-0:amd64 1.0.2-2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libde265_1.0.2-1ppa2~trusty1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Do you have any leads for me ? Thanks

**Comment by fancycode** [comment]
With Ubuntu 16.04 you don't need the PPA to install libde265 (it is included in the official repository). The package name in Ubuntu however is slightly different from our PPA, so you will encounted problems if you try to install both. Also the PPA doesn't provide packages for 16.04 - how did you enable it?

Manually installing from the PPA *might* work if you uninstall `libde265-0` from the official repository and the install everything from the PPA.

However to install the `vlc-plugin-libde265` for 16.04 the better solution is probably that we provide the package directly for that Ubuntu release and build it against the libde265 package from Upstream. I'll put that on my list...

**Comment by thiswillbeyourgithub** [comment]
>how did you enable it

It was a long time ago :/ i'm sorry

Oh okay so I should uninstall `libde265` and remove the ppa, then install `libde265-0` ? And just wait for `vlc-plugin-libde265` to appear in the official repositories right ?

**Comment by fancycode** [comment]
It looks like you are still using the (old) PPA configuration that installs Trusty packages, even though you upgraded to Xenial. You should uninstall `libde265`, remove the old PPA configuration and re-add the PPA to get Xenial packages.

I just uploaded `vlc-plugin-libde265` for Xenial to the PPA [1]. Once it's done building, you can install it from the (Xenial) PPA and it will use `libde265-0` from the official repository.

[1] https://launchpad.net/~strukturag/+archive/ubuntu/libde265/+packages

**Comment by thiswillbeyourgithub** [comment]
I think it solved my issue. Thanks a lot !
