### ISSUE TITLE
JavaScript decoder

### ISSUE THREAD

**Issue by gedw99** [strukturag/libde265#163]
This looks brilliant !

When I tried the web demo I noticed the frame rate was only 2 or 3 frames a second.
It was my Android chrome browser.

Curious if this is what is to be expected ?
Also I guess your compiling to WASM - did not check but it should help.
Also it might work better in a web worker. Lots of tradeoffs with that but am curious if you looked at that approach.

**Comment by gedw99** [comment]
looks like i spoke to soon :)
https://github.com/strukturag/libde265.js
At the very bottom of the Readme.md you list webworkers as a known optimisation.
Do you want help with that ?

**Comment by fancycode** [comment]
We are already using a webworker to offload color conversion (YUV -> RGB), but it might also improve performance to move the actual decoding to a webworker (we haven't tested this though).

Anyway, pull-requests to https://github.com/strukturag/libde265.js are always welcome!

**Comment by gedw99** [comment]
thanks for the clarification.

I will see if i get time to work on the decoder inside a webworker.

I have not looked at the code in depth, but web workers can ONLY pass messages to the Main thread. Are you sure thats no a SPOP ( single point of performance ) bottleneck and so makes doing the decoding inside a webworker pointless ??
