### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DomT4** [strukturag/libde265#166]
Any chance of a new stable release here?

The current 1.0.2 released in 2015 doesn't compile using recent versions of `clang`, which is a problem already fixed in the master branch here, so having that available as part of a stable release would be useful & appreciated. Thanks!

**Comment by shakingWaves** [comment]
How to derive the Table entropy_table[128] ?

**Comment by farindk** [comment]
1.0.3 has been released for which I am not aware of any clang problems.
If you still have any compilation problems with 1.0.3, please attach a full log here.

**Comment by DomT4** [comment]
Builds fine on macOS 10.13 using Apple LLVM version 9.1.0 (clang-902.0.39.1) so 👍. Closing as fixed. Thank you!
