### ISSUE TITLE
entropy_table_orig

### ISSUE THREAD

**Issue by shakingWaves** [strukturag/libde265#173]
The array entropy_table_orig was derived from HEVC proposal JCTVC-G0763. I have read it, But, I also do not know how to get the array. I am curious about the method of computing the array entropy_table_orig. Can you give me some hints?

**Comment by farindk** [comment]
G0763 says:
"This new table was derived using the table defining the LPS ranges for each state. When deriving this new table it was assumed that the range register in the CABAC engine takes value R with a probability proportional to 1/R."

If you would like to know more details, I suggest that you contact the author of G0763, as he has written the code to derive the table and he did not publish the code (as far as I know).
