### ISSUE TITLE
entropy_table

### ISSUE THREAD

**Issue by shakingWaves** [strukturag/libde265#174]
I have compared the performance of entropy_tab vs. entropy_tab_org,
list below:

  | Y | U | V
-- | -- | -- | --
Class B | 0.00% | -0.14% | -0.13%
Class C | 0.00% | -0.09% | -0.09%
Class D | 0.00% | -0.11% | -0.08%
Class E | 0.01% | -0.16% | -0.15%
Class F   (optional) | 0.00% | -0.07% | -0.07%

entropy_tab have BD-Rate gain in U and V component of all sequence,
But, have BD-Rate loss in Y component of sequence class E.

I have understand your method of producing array entropy_tab.
and I have try to contact Frank Bossen, the autor of JCTVC-G0763, many times, But still can't contact him.

**Comment by farindk** [comment]
The table looks fine to me. The entropy table only gives an estimate of the number of bits used to allow the encoder do a fast mode decision. Hence, a tiny deviation like you see in Y for Class E is nothing I would worry about.

**Comment by shakingWaves** [comment]
Table rangeTabLps which was corresponding to Table 9-46 in standard specification, lists all lps range of every state.
But, rangeTabLps still exists "interval inversion" problem, that is, the subinterval for the MPS may be smaller than the subinterval for the LPS.
for example:
	pStateIdx equals to 1 and qRangeIdx equals to 2, and lps symbol occurs,
	then m_uiRange equals to 167 which was smaller than 256, so m_uiRange = (m_uiRange << 1) = 334,
	
	because of lps symbol, the pStateIdx will translate to 0 and
	uiLPS   = TComCABACTables::sm_aucLPSTable[0][ ( 334 >> 6 ) & 3 ] = 176,
	so, mps_range = m_uiRange - uiLPS = 334 - 176 = 158,
	which will cause mps_range < lps_range, that is a bug?

**Comment by farindk** [comment]
For any issues with the HM encoder, contact the respective people. This is the issue tracker for libde265.
