### ISSUE TITLE
rangeTabLps error?

### ISSUE THREAD

**Issue by shakingWaves** [strukturag/libde265#175]
Table rangeTabLps which was corresponding to Table 9-46 in standard specification, lists all lps range of every state.
But, rangeTabLps still exists "interval inversion" problem, that is, the subinterval for the MPS may be smaller than the subinterval for the LPS.
for example:
pStateIdx equals to 1 and qRangeIdx equals to 2, and lps symbol occurs,
then m_uiRange equals to 167 which was smaller than 256, so m_uiRange = (m_uiRange << 1) = 334,

because of lps symbol, the pStateIdx will translate to 0 and
uiLPS   = TComCABACTables::sm_aucLPSTable[0][ ( 334 >> 6 ) & 3 ] = 176,
so, mps_range = m_uiRange - uiLPS = 334 - 176 = 158,
which will cause mps_range < lps_range, that is a bug?

**Comment by farindk** [comment]
For any issues with the HM encoder, contact the respective people. This is the issue tracker for libde265.
