### ISSUE TITLE
Build libde265 without the encoder

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libde265#178]
In the @ImageMagick project we keep a copy of the released versions in our own repository and use that to build ImageMagick with libde265 support under Windows. In the previous version we could build the library without the encoder (that we dont use) by excluding the `en265.cc` file and the `encoder` folder. But in the latest release the file `intrapred.cc` and `motion.cc` use code from the encoder part. In the future we will use the libde265 encoder but for now it would be nice if there still was an option to exclude the code of the coder.

**Comment by farindk** [comment]
Ok, I will refactor that.

**Comment by farindk** [comment]
Encoder source has been separated from the decoder in 85086b467310cbd27fb115f8fe94a519db2ed3c8.
You can simply omit the directory `encoder` from compiling. Also omit compiling the file `en265.cc` in this case.
There is also a `configure`-option to disable compiling the encoder.

**Comment by dlemstra** [comment]
Thanks for the quick patch @farindk !
