### ISSUE TITLE
Read access violation in static build on Windows

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libde265#254]
I am not sure how to properly describe our issue but we are having some problems with the latest release of libde265 due to some changes in `de265.cc`. The call to `std::lock_guard<std::mutex> lock(de265_init_mutex)` causes an exception: `_Mtx_internal_imp_t::_get_cs(...)-> was nullptr`. This only appears to happen with the static build of @ImageMagick. We don't have any problems with a dynamic build. I don't know why this happens and I could not find any good information on why this could be a problem. We are calling the library code from our `C` code. I wonder if it is possible to have the `mutex` as a `static` variable. We did not have this problem when `std::atomic<int>` was used.

**Comment by Nevcairiel** [comment]
I'm facing the same issue. Static initialization is evil and should be avoided. I would strongly urge for either an explicit init function, or an atomic initialization when the user calls into the API for the first time (ie. using std::call_once or similar).
