### ISSUE TITLE
enc265 not working on MSVS2019

### ISSUE THREAD

**Issue by dmitry1945** [strukturag/libde265#270]
Hi All,

I have build the cmake project with MSVS2019 and I have run the encoder with yuv file. This is the command line arguments:
`-i c:\Work\Espressif\Tech\Arrow\Linux\Video_stream\openh264\res\CiscoVT2people_320x192_12fps.yuv -v -w 320 -h 192`
The first frame works fine, and then on the second frame I always get next error:
`Assertion failed: PartMode==PART_Nx2N, file C:\Work\Espressif\Tech\Arrow\Linux\Video_stream\libde265\libde265\encoder\encoder-syntax.cc, line 201`
I have try to build on Linux and there I have the same error.

What do I wrong? Is it wrong settings, or something else?

Thanks,
Dmitry

PS. It's very-very good that you made cmake build. Thank you!

**Comment by farindk** [comment]
The encoder part is far from working. It works for intra-frames (your first frame), but everything else is not finished and at the moment, nobody is working on the encoder part.

**Comment by dmitry1945** [comment]
Thanks for the fast answer.

Regards,
Dmitry
