### ISSUE TITLE
libde265 error resilience/concealment 

### ISSUE THREAD

**Issue by jasa23** [strukturag/libde265#281]
Hello,
I would like to know how this decoder reacts to a packet loss.
does it have a strategy of error concealment?
thank you

**Comment by farindk** [comment]
libde265 tracks which frames had decoding errors and also flags images that depend on faulty references. See the option
````
  DE265_DECODER_PARAM_SUPPRESS_FAULTY_PICTURES=6, // (bool)  do not output frames with decoding errors, default: no (output all images)                                                                                                                                                                                       
````
However, it does not do any concealment, e.g. by filling in artificial content in those areas.

**Comment by jasa23** [comment]
@farindk 
thanks but I didn't understand how he replaces these areas with artificial content
could you explain me a little more please

**Comment by farindk** [comment]
libde265 does _not_ fill in any artificial content. The content will be random or plain grey or green.

**Comment by jasa23** [comment]
@farindk 
ok 
thank you
