### ISSUE TITLE
FFMpeg remux issue for libde265 generated mkv files

### ISSUE THREAD

**Issue by adams79** [strukturag/libde265#296]
When using FFmpeg to remux a libde265 generated mkv file to mp4 it generate an invalid output file.

The simple command the I use and works for all other MKV files is the following:

 ffmpeg -i source.mkv -c:v copy -tag:v hvc1  output.mp4

By trying to analyze the generated file with ffprobe I see the following error:
[extract_extradata @ 0x7fd9abc176c0] Invalid NAL unit 0, skipping.
[hevc @ 0x7fd9ac00b000] Invalid NAL unit 0, skipping.
[extract_extradata @ 0x7fd9abc176c0] No start code is found.
tos-1720x720-cfg01.mp4: Invalid data found when processing input

Any other files generated using other h265 library works correctly when muxed.

Any hint?

**Comment by farindk** [comment]
libde265 does not generate any mkv files and it's a decoder. Thus, I don't understand the question...

**Comment by adams79** [comment]
I'm sorry, I've already closed the issue. The problem is that file downloaded from libde265 site has shown this remux problem with FFMPG so I wrongly assumed that videos are encoding samples for the library.

**Comment by farindk** [comment]
Those were multiplexed with `mkvtoolnix`, if that helps. I think they were encoded with the HM reference encoder.

**Comment by adams79** [comment]
Thank you,
for some strange reason FFMPEG is not able to parse that files correctly, also by trying a direct stream copy from MKV to MKV I got "Invalid data found when processing input"
However I'm able to extract that tracks with mkvextract for example getting only some warning:

Warning: bbb-1280x720-cfg02.mkv: Error in the Matroska file structure at position 66183963. Resyncing to the next level 1 element.
Warning: The last timestamp processed before the error was encountered was 00:05:49.120333331.
Warning: Resyncing successful at position 88445421.
Warning: The first cluster timestamp after the resync is 00:07:18.283000000.

I'm running out of ideas, I'm worried that I will face the same problem on other files as well...
