### ISSUE TITLE
Coding command

### ISSUE THREAD

**Issue by xiaobaicai004** [strukturag/libde265#309]
I used yuv and mkv materials for encoding, and the following error was reported during encoding. I don't know if the input command is wrong
![微信截图_20211129153553](https://user-images.githubusercontent.com/23447513/143828800-2a429e9c-899c-4d94-b1f2-b292afc43bd8.png)

Operating system: window10
Compilation tool: vs2015 x64 /cmake

**Comment by xiaobaicai004** [comment]
Is there a command line codec example?

**Comment by farindk** [comment]
The encoder`enc265` is incomplete and will probably not be developed further. Use x265 instead.
