### ISSUE TITLE
Integer-overflow · residual_coding

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libde265#322]
The https://github.com/ImageMagick project is using the oss-fuzz tooling of google and with the attached file there is an integer overflow in `residual_coding`. I suspect that this is caused by returning a negative value in `decode_coeff_abs_level_remaining`.

https://github.com/strukturag/libde265/blob/e587ef6e8000662b91c35ccb866c2374d3a40e27/libde265/slice.cc#L3369

Test file: [test.zip](https://github.com/strukturag/libde265/files/9033582/test.zip)

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48430

**Comment by farindk** [comment]
I was not able to reproduce this issue. I tried with old versions back to v1.0.8 and on old Ubuntu 16.04.
h265 stream extracted from test.heic: [issue322.zip](https://github.com/strukturag/libde265/files/10519174/issue322.zip)

**Comment by dlemstra** [comment]
Bug has been marked as fixed on the oss-fuzz website so I will close this.
