### ISSUE TITLE
Undefined-shift in decode_CABAC_FL_bypass

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libde265#325]
The https://github.com/ImageMagick project is using the oss-fuzz tooling of google and with the attached file there is an undefined shift with a negative value (-570425344) in `decode_CABAC_FL_bypass`

https://github.com/strukturag/libde265/blob/e587ef6e8000662b91c35ccb866c2374d3a40e27/libde265/cabac.cc#L397

[test.zip](https://github.com/strukturag/libde265/files/9034730/test.zip)

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48114

**Comment by farindk** [comment]
I was not able to reproduce this issue. I tried with old versions back to v1.0.8 and on old Ubuntu 16.04.
h265 stream extracted from test.heic: [issue325.zip](https://github.com/strukturag/libde265/files/10519235/issue325.zip)

**Comment by dlemstra** [comment]
I am seeing this on windows with a debugger attached:

![afbeelding](https://user-images.githubusercontent.com/10426229/215136964-579d06f4-982a-4108-bc9e-fc47210e2e2f.png)

Probably happening because of this:

![afbeelding](https://user-images.githubusercontent.com/10426229/215137346-a0a5b707-d248-46a4-94f9-ab91b4cb0ec5.png)

**Comment by farindk** [comment]
Thanks. Yes, that makes sense. It's just strange that I don't get to that condition when trying with the same input. Probably some undefined behavior because of a decoding error before that.

Could you please also attach a stack trace that I can see the call stack that ultimatively calls `decode_CABAC_FL_bypass()` ?

**Comment by dlemstra** [comment]
I am using ImageMagick to reproduce this so my stacktrace might be a bit different:

```
CORE_DB_heif_.dll!decode_CABAC_FL_bypass(CABAC_decoder * decoder, int nBits) Line 396	C++
CORE_DB_heif_.dll!decode_coeff_abs_level_remaining(thread_context * tctx, int cRiceParam) Line 2480	C++
CORE_DB_heif_.dll!residual_coding(thread_context * tctx, int x0, int y0, int log2TrafoSize, int cIdx) Line 3348	C++
CORE_DB_heif_.dll!read_transform_unit(thread_context * tctx, int x0, int y0, int xBase, int yBase, int xCUBase, int yCUBase, int log2TrafoSize, int trafoDepth, int blkIdx, int cbf_luma, int cbf_cb, int cbf_cr) Line 3662	C++
CORE_DB_heif_.dll!read_transform_tree(thread_context * tctx, int x0, int y0, int xBase, int yBase, int xCUBase, int yCUBase, int log2TrafoSize, int trafoDepth, int blkIdx, int MaxTrafoDepth, int IntraSplitFlag, PredMode cuPredMode, unsigned char parent_cbf_cb, unsigned char parent_cbf_cr) Line 3966	C++
CORE_DB_heif_.dll!read_transform_tree(thread_context * tctx, int x0, int y0, int xBase, int yBase, int xCUBase, int yCUBase, int log2TrafoSize, int trafoDepth, int blkIdx, int MaxTrafoDepth, int IntraSplitFlag, PredMode cuPredMode, unsigned char parent_cbf_cb, unsigned char parent_cbf_cr) Line 3940	C++
CORE_DB_heif_.dll!read_coding_unit(thread_context * tctx, int x0, int y0, int log2CbSize, int ctDepth) Line 4576	C++
CORE_DB_heif_.dll!read_coding_quadtree(thread_context * tctx, int x0, int y0, int log2CbSize, int ctDepth) Line 4651	C++
CORE_DB_heif_.dll!read_coding_quadtree(thread_context * tctx, int x0, int y0, int log2CbSize, int ctDepth) Line 4641	C++
CORE_DB_heif_.dll!read_coding_tree_unit(thread_context * tctx) Line 2862	C++
CORE_DB_heif_.dll!decode_substream(thread_context * tctx, bool block_wpp, bool first_independent_substream) Line 4742	C++
CORE_DB_heif_.dll!read_slice_segment_data(thread_context * tctx) Line 5049	C++
CORE_DB_heif_.dll!decoder_context::decode_slice_unit_sequential(image_unit * imgunit, slice_unit * sliceunit) Line 843	C++
CORE_DB_heif_.dll!decoder_context::decode_slice_unit_parallel(image_unit * imgunit, slice_unit * sliceunit) Line 945	C++
CORE_DB_heif_.dll!decoder_context::decode_some(bool * did_work) Line 730	C++
CORE_DB_heif_.dll!decoder_context::read_slice_NAL(bitreader & reader, NAL_unit * nal, nal_header & nal_hdr) Line 688	C++
CORE_DB_heif_.dll!decoder_context::decode_NAL(NAL_unit * nal) Line 1230	C++
CORE_DB_heif_.dll!decoder_context::decode(int * more) Line 1318	C++
CORE_DB_heif_.dll!de265_decode(void * de265ctx, int * more) Line 351	C++
CORE_DB_heif_.dll!libde265_v1_decode_image(void * decoder_raw, heif_image * * out_img) Line 324	C++
CORE_DB_heif_.dll!heif::HeifContext::decode_image_planar(unsigned int ID, std::shared_ptr<heif::HeifPixelImage> & img, heif_colorspace out_colorspace, const heif_decoding_options * options, bool alphaImage) Line 1181	C++
CORE_DB_heif_.dll!heif::HeifContext::decode_image_user(unsigned int ID, std::shared_ptr<heif::HeifPixelImage> & img, heif_colorspace out_colorspace, heif_chroma out_chroma, const heif_decoding_options * options) Line 1088	C++
CORE_DB_heif_.dll!heif_decode_image(const heif_image_handle * in_handle, heif_image * * out_img, heif_colorspace colorspace, heif_chroma chroma, const heif_decoding_options * options) Line 947	C++
IM_MOD_DB_heic_.dll!ReadHEICImageHandle(const _ImageInfo * image_info, _Image * image, heif_image_handle * image_handle, _ExceptionInfo * exception) Line 365	C
```

Seeing a thread context so maybe this is related to threading?

**Comment by farindk** [comment]
Thanks for the stack trace.
It shouldn't be because of multi-threading, because each thread is working on its own part of the bitstream.

This kind of overflow is hard to avoid because the way the bitstream is constructed, there is no limit for the number of bits in this symbol except that a conformance bitstream _should not_ contain more bits. If I put a bitstream error check in there, it will be in the innermost loops and may hurt performance. Thus it's a tradeoff. In the end, nothing bad will happen from the overflow.

**Comment by dlemstra** [comment]
I have updated the stack trace for when the value is `60` this is slightly different. But if you think the return value having a random value won't be an issue we can close this.

**Comment by farindk** [comment]
Maybe the above change is the easiest fix. I've simply made the variable to hold the read value unsigned. Then, the shift shouldn't be undefined anymore. Right?

**Comment by dlemstra** [comment]
Yeah that should probably fix this.
