### ISSUE TITLE
Wrong library shared object name when using Cmake build system

### ISSUE THREAD

**Issue by dmilith** [strukturag/libde265#360]
SO to make the long story short, when I build libde265 from the source using autotools (configure script) it produces a shared object named "libde265.so".

But! When I'll use cmake build system, the produced shared object name is "liblibde265.so", which makes it undetectable by external projects like ImageMagick:
https://github.com/ImageMagick/ImageMagick/issues/5783

**Comment by farindk** [comment]
Does the above commit fix this for you?
