### ISSUE TITLE
Win: Name of library has changed to "de265.dll"

### ISSUE THREAD

**Issue by fancycode** [strukturag/libde265#390]
Some recent commit has changed the library on Windows from `libde265.dll` to `de265.dll`. This should be changed back to stay compatible with existing applications using the library.

Extracted from #389

@farindk FYI

**Comment by fancycode** [comment]
Once changed, the AppVeyor CI script must be updated in https://github.com/strukturag/libde265/blob/3aea5a45ce234ff117f116448417c7ccfdc4e6a8/appveyor.yml#L34

**Comment by farindk** [comment]
Fixed in #392.
