### ISSUE TITLE
libde265 unit tests

### ISSUE THREAD

**Issue by vpa1977** [strukturag/libde265#424]
MIR review for Libde265 noted the absence of the unit tests [1].
Would it be possible to consider adding a set of tests for the library? 
I am happy to work on this issue.

[1] https://bugs.launchpad.net/ubuntu/+source/libde265/+bug/2004449

**Comment by farindk** [comment]
The CI runs the decoder with a large set of teststreams:
https://github.com/strukturag/libde265/actions/workflows/decode.yml

It is fuzzed indirectly through libheif (CI and oss-fuzz):
https://bugs.chromium.org/p/oss-fuzz/issues/list?q=libheif

What other kind of tests do you propose?

**Comment by vpa1977** [comment]
I was considering a small smoke test that can run during package build in Ubuntu or Debian - something similar to aom test suite, or just an autopkgtest that runs over some small (a few frames) streams.

The streams used in the decode workflow can not be included in the packaging due to the license concerns.

**Comment by vpa1977** [comment]
This is already merged on salsa =) 

I was wondering if it would be ok to add a small bitreader google test to detect issues with big endian systems?

**Comment by farindk** [comment]
> This is already merged on salsa =)

Ok, I didn't see this as @fancycode does the Debian packaging.

> I was wondering if it would be ok to add a small bitreader google test to detect issues with big endian systems?

This or simply decoding the video on big endian systems should also show the error.
We can run the video output through `md5sum` to check whether everything is correct.
h265 guarantees that decoding is pixel exact.

**Comment by farindk** [comment]
I have encoded a small video clip. You can test for correct decoding by passing the output through `md5sum` like this:
````
$ ./dec265 ../testdata/girlshy.h265 -q -o - 2>/dev/null|md5sum -
b81538fa33a67278e5263e231e43ca98  -
````

**Comment by vpa1977** [comment]
Thank you!!! I will add PR on salsa to use it in autopkgtest/build smoke test when the new version is available.

**Comment by farindk** [comment]
PS: see the last lines in `scripts/ci-run.sh`. I've also added the test there.
