### ISSUE TITLE
dump header info 

### ISSUE THREAD

**Issue by ggeor** [strukturag/libde265#57]
hi, 

i use -d option to dump headers while decoding a stream with multiple tiles and one slice per frame...but when i see the info, i see multiple slices, even if i decode one frame (using option -f 1) ....for example i decode one frame with one slice and 4 tiles....shouldn't i see 1 slice and 3 entry points? Instead there seem to be 4 slices info with respective entry points

**Comment by StaZhu** [comment]
Hello guys!  would you mind attach a link of a multi slice hevc sample here? I am trying to find a sample to test the decoding code but not able to find any of them. @ggeor @farindk
