### ISSUE TITLE
sub-layer non-reference picture in process_picture_order_count

### ISSUE THREAD

**Issue by noxmetus** [strukturag/libde265#60]
“Sub-layer non-reference picture” case in
```cpp
  if (1 /* TemporalID==0 */ && // TODO
      (isReferenceNALU(ctx->nal_unit_type) &&
       (!isRASL(ctx->nal_unit_type) && !isRADL(ctx->nal_unit_type))) &&
      1 /* sub-layer non-reference picture */) // TODO
```
is actually managed by `isReferenceNALU(ctx->nal_unit_type)`. See 7.4.2.2 of ITU-T H.265:
>If a picture has nal_unit_type equal to TRAIL_N, TSA_N, STSA_N, RADL_N, RASL_N, RSV_VCL_N10, RSV_VCL_N12, or RSV_VCL_N14, the picture is a sub-layer non-reference picture. Otherwise, the picture is a sublayer reference picture.

So you can remove `&& 1 /* sub-layer non-reference picture */` along with the last TODO.

**Comment by farindk** [comment]
Thanks.
fixed in e4723f46db59a9237135811506d08408a5e17887
