### ISSUE TITLE
iPhone 4 app not decoding

### ISSUE THREAD

**Issue by chuckleplant** [strukturag/libde265#90]
Hi, got redirected here from the app store. 
I can't decode anything from the iPhone app. The app shows a couple frames and audio is fine (sometimes) but then it freezes. Is the iPhone 4 supported?

Best!

**Comment by Ivansss** [comment]
Hi,
What are the resolutions of the videos you are trying to decode?
Maybe the problem here is that iPhone 4 does not have enough processing power to decode that kind of videos.

**Comment by chuckleplant** [comment]
I've tried 1280x720. I'll try half of that and see if it works.
