### ISSUE TITLE
Autoconf undefined macros on Debian 7.8

### ISSUE THREAD

**Issue by ryandalzell** [strukturag/libde265#92]
On Debian 7.8 (wheezy)

```
> autogen.sh
[...]
configure.ac:10: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:96: error: possibly undefined macro: AC_DEFINE
```

I tried hacking it with m4_pattern_allow, but it just failed in the ./configure instead.

**Comment by fancycode** [comment]
Which version of `autoconf` / `automake` are you using? Do you have `pkg-config` installed on your machine? See http://stackoverflow.com/questions/8811381/possibly-undefined-macro-ac-msg-error for a similar issue.

**Comment by ryandalzell** [comment]
```
apt-get install pkg-config
```

Fixes this.

Many thanks for your help, I was completely stuck.
